export const OrderStatus = {
  PENDING_ASSIGN: 'PENDING_ASSIGN',
  ASSIGNED: 'ASSIGNED',
  ON_THE_WAY: 'ON_THE_WAY',
  ARRIVED_PICKUP: 'ARRIVED_PICKUP',
  WAITING_PASSENGER: 'WAITING_PASSENGER',
  PASSENGER_BOARDED: 'PASSENGER_BOARDED',
  ARRIVING_DESTINATION: 'ARRIVING_DESTINATION',
  ARRIVED_DESTINATION: 'ARRIVED_DESTINATION',
  PENDING_FEE_CONFIRM: 'PENDING_FEE_CONFIRM',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  ABNORMAL_PROCESSING: 'ABNORMAL_PROCESSING',
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]
